# Generated by Django 5.2.2 on 2025-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reward',
            name='points_required',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
