# Generated by Django 5.2.2 on 2025-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_reward_price_alter_reward_points_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='price',
        ),
        migrations.AlterField(
            model_name='reward',
            name='points_required',
            field=models.PositiveIntegerField(),
        ),
    ]
