# Generated by Django 5.2.2 on 2025-09-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_reward_amount_discount_reward_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Points per dollar (e.g., 5.00 for 5 points per $1)', max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Points Rate',
                'verbose_name_plural': 'Points Rates',
            },
        ),
    ]
