# Generated by Django 5.2.2 on 2025-09-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_pointsrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
