# Generated by Django 5.2.2 on 2025-09-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_redemption_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
