# Generated by Django 5.2.2 on 2025-09-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0008_redemption_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
